### ISSUE TITLE
Enhance shenyu-plugin-dubbo module unit test 

### ISSUE THREAD

**Issue by ttttangzhen** [dromara/shenyu#1455]
## Task

Task List:

- [x]  Enhance shenyu-plugin-alibaba-dubbo module unit test，make its coverage rate is more than 80%
- [x] Enhance shenyu-plugin-apache-dubbo module unit test，make its coverage rate is more than 80%
- [x] Enhance shenyu-plugin-dubbo-common module unit test，make its coverage rate is more than 80%

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by wyc192273** [comment]
I want shenyu-plugin-dubbo-common task

**Comment by yiwenlong** [comment]
Please assign `shenyu-plugin-apache-dubbo` to me.

**Comment by wyc192273** [comment]
Please assign shenyu-plugin-alibaba-dubbo  task to me.
