### ISSUE TITLE
Enhance shenyu-register-center module unit test

### ISSUE THREAD

**Issue by zhaiweij** [dromara/shenyu#1457]
## Task

A clear and concise description of Task

Task List:

- [ ] Enhance shenyu-register-client module unit test，make its coverage rate is more than 80%
- [ ] Enhance shenyu-register-common module unit test，make its coverage rate is more than 80%
- [ ] Enhance shenyu-register-server module unit test，make its coverage rate is more than 80%

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by useaname** [comment]
I want Enhance  shenyu-register-client module unit test

**Comment by wyc192273** [comment]
Please assign shenyu-register-common module unit test to me.

**Comment by zhaiweij** [comment]
> Please assign shenyu-register-common module unit test to me.

You can send an email to me

**Comment by zhaiweij** [comment]
> I want Enhance shenyu-register-client module unit test

You can send an email to me

**Comment by wxyyrain** [comment]
I want Enhance shenyu-register-server module unit test

**Comment by zhaiweij** [comment]
can you Enhance shenyu-register-client-http ？


| |
zhaiweij
|
|
***@***.***
|
签名由网易邮箱大师定制


On 05/14/2021 ***@***.***> wrote：

I want Enhance shenyu-register-client module unit test

**Comment by zhaiweij** [comment]
No test is required under the common module ，can you enhance shenyu-register-client-nacos?



| |
zhaiweij
|
|
***@***.***
|
签名由网易邮箱大师定制


On 05/14/2021 ***@***.***> wrote：

Please assign shenyu-register-common module unit test to me.

**Comment by zhaiweij** [comment]
can you enhance shenyu-register-server-nacos?


| |
zhaiweij
|
|
***@***.***
|
签名由网易邮箱大师定制


On 05/14/2021 ***@***.***> wrote：

I want Enhance shenyu-register-server module unit test

**Comment by wyc192273** [comment]
> No test is required under the common module ，can you enhance shenyu-register-client-nacos? | | zhaiweij | | ***@***.*** | 签名由网易邮箱大师定制 On 05/14/2021 ***@***.***> wrote： Please assign shenyu-register-common module unit test to me. — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes. i can. shenyu-register-client-nacos also need enhance?

**Comment by zhaiweij** [comment]
> > No test is required under the common module ，can you enhance shenyu-register-client-nacos? | | zhaiweij | | _**@**_.*** | 签名由网易邮箱大师定制 On 05/14/2021 _**@**_.***> wrote： Please assign shenyu-register-common module unit test to me. — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Yes. i can. shenyu-register-client-nacos also need enhance?

yes，the method is 66% 4/6

**Comment by wxyyrain** [comment]
> can you enhance shenyu-register-server-nacos? | | zhaiweij | | ***@***.*** | 签名由网易邮箱大师定制 On 05/14/2021 ***@***.***> wrote： I want Enhance shenyu-register-server module unit test — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

ok, i will do it

**Comment by wyc192273** [comment]
> > > No test is required under the common module ，can you enhance shenyu-register-client-nacos? | | zhaiweij | | _**@**_.*** | 签名由网易邮箱大师定制 On 05/14/2021 _**@**_.***> wrote： Please assign shenyu-register-common module unit test to me. — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > Yes. i can. shenyu-register-client-nacos also need enhance?
> 
> yes，the method is 66% 4/6

Ok.Let me do it.
