### ISSUE TITLE
Enhance shenyu-spring-boot-starter module unit test

### ISSUE THREAD

**Issue by qiaoqia** [dromara/shenyu#1459]
## Task

A clear and concise description of Task

Task List:
### shenyu-spring-boot-starter-plugin
   - [ ] Enhance shenyu-spring-boot-starter-plugin-httpclient module unit test，make its coverage rate is more than 80%
   - [ ] Enhance shenyu-spring-boot-starter-plugin-logging module unit test，make its coverage rate is more than 80%
### shenyu-spring-boot-starter-sync-data-center
   - [ ] Enhance shenyu-spring-boot-starter-sync-data-nacos module unit test，make its coverage rate is more than 80%

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by songyuequan** [comment]
please sign  shenyu-spring-boot-starter-plugin-httpclient module unit test  To me

**Comment by songyuequan** [comment]
please sign  shenyu-spring-boot-starter-plugin-httpclient module unit test  To me

**Comment by zendwang** [comment]
please sign shenyu-spring-boot-starter-sync-data-nacos module unit test to me

**Comment by renzhuyan** [comment]
get task Enhance shenyu-spring-boot-starter-plugin-logging module unit test，make its coverage rate is more than 80%
