### ISSUE TITLE
Add test for ParameterData

### ISSUE THREAD

**Issue by yu199195** [dromara/shenyu#1508]
## Task

add ParameterDataTest for Coverage CookieParameterData， HeaderParameterData， HostParameterData ， IpParameterData

PostParameterData，QueryParameterData，RequestMethodParameterData， URIParameterData

Task List:

- [x] add ParameterDataFactoryTest @FocusZhouGD
- [x] add CookieParameterDataTest
- [x] add HeaderParameterDataTest @cchenxi
- [x] add HostParameterDataTest
- [x] add IpParameterDataTest  @tangtian8 
- [x] add PostParameterDataTest @xxl115
- [x] add QueryParameterDataTest  @winfred958
- [x] add RequestMethodParameterDataTest @xxl115
- [x] add URIParameterDataTest @useaname 

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by useaname** [comment]
Please assign to me add URIParameterDataTest.

**Comment by tangtian8** [comment]
add URIParameterDataTest give me tks

**Comment by xxl115** [comment]
Please assign to me add RequestMethodParameterDataTest

**Comment by winfred958** [comment]
Please assign to me add QueryParameterDataTest.

**Comment by xxl115** [comment]
Please assign to me add PostParameterDataTest

**Comment by Banana1995** [comment]
I'm interesting in add HostParameterDataTest ,pls assign to me , thanks

**Comment by cchenxi** [comment]
Please assign to me add HeaderParameterDataTest.

**Comment by FocusZhouGD** [comment]
Please assign to me add ParameterDataFactoryTest
