### ISSUE TITLE
Zookeeper synchronization remove java serialization

### ISSUE THREAD

**Issue by zhaiweij** [dromara/shenyu#1563]
## Task

A clear and concise description of Task

Task List:

- [ ] remove ZookeeperDataChangedListener sync java serialization
- [ ] remove ZookeeperSyncDataService sync java serialization
- [ ] the serialization of java bea under the org.apache.shenyu.common.dto package

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by yu199195** [comment]
good idea !
